### ISSUE TITLE
Method does not exist: math

### ISSUE THREAD

**Issue by muuvmuuv** [Corjen/gatsby-plugin-polished#1]
I don't know if this is a polished problem but I think its a babel error. I get this all the time:

```shell
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: /Users/marvinheilemann/Documents/Projects/M8Finder/gatsby.m8finder.net/src/theme.ts: Method does not exist: math
> 1 | import { hsl, math, setSaturation } from 'polished'
```

**Comment by Corjen** [comment]
Hi @muuvmuuv,

Could you make a reproducible example in codesandbox? And did you try updating polished and the babel-plugin?

**Comment by muuvmuuv** [comment]
@Corjen I'wll try to. I think everything is up-to-date:

"babel-plugin-polished": "^1.1.0",
"polished": "^3.0.3",

**Comment by muuvmuuv** [comment]
@Corjen Okay, I can't handle codesandbox :D sry. Here is what I tried: https://codesandbox.io/s/3vmlkmyz7m

**Comment by Corjen** [comment]
Hi @muuvmuuv, the problem doens't seem related to this plugin. The only thing it does is adding babel-plugin-polished to the babel config of gatsby.

If i'm manually adding a .babelrc config it get the same issue. I saw you added an issue to the babel-plugin-polished repo, the problem probably lies there.

For now, you can just not use the babel plugin, it's a small optimisation anyway :)
